using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace SoftGL
{
    class VertexArrayObject
    {
        private uint[] ids = new uint[1];

        /// <summary>
        /// name generated by glGenTextures(..).
        /// </summary>
        public uint Id { get { return this.ids[0]; } }

        public VertexArrayObject(uint id)
        {
            this.ids[0] = id;
        }

        /// <summary>
        ///
        /// </summary>
        /// <returns></returns>
        public override string ToString()
        {
            return string.Format("Vertex Array Object: Id:{0}, T:{1}", this.ids);
        }
    }
}
