using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace SoftGL
{
    class GLBuffer
    {
        public BindBufferTarget Target { get; private set; }

        private uint[] ids = new uint[1];

        /// <summary>
        /// name generated by glGenTextures(..).
        /// </summary>
        public uint Id { get { return this.ids[0]; } }

        /// <summary>
        /// Creates a buffer object.
        /// </summary>
        public GLBuffer(BindBufferTarget target, uint id)
        {
            this.Target = target;
            this.ids[0] = id;
        }

        /// <summary>
        ///
        /// </summary>
        /// <returns></returns>
        public override string ToString()
        {
            return string.Format("Texture: Id:{0}, T:{1}", this.ids, this.Target);
        }
    }
}
