using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace SoftGL
{
    /// <summary>
    /// Bind a <see cref="Sampler"/> object to a texture uint('s index), and it will affect all textures that bind to the same texture uint.
    /// </summary>
    partial class Sampler : List<SamplerParameter>
    {
        private uint[] ids = new uint[1];

        /// <summary>
        /// name generated by glGenSamplers(..).
        /// </summary>
        public uint Id { get { return this.ids[0]; } }

        /// <summary>
        /// Creates a sampler object.
        /// </summary>
        public Sampler(uint id) { this.ids[0] = id; }

        /// <summary>
        ///
        /// </summary>
        /// <returns></returns>
        public override string ToString()
        {
            return string.Format("Sampler: Id:{0}", this.ids);
        }
    }
}
