using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace SoftGL
{
    class ShaderProgram
    {
        /// <summary>
        /// name generated by glCreateProgram().
        /// </summary>
        public uint Id { get; private set; }

        /// <summary>
        /// Creates a program object.
        /// </summary>
        public ShaderProgram(uint id)
        {
            this.Id = id;
        }

        /// <summary>
        ///
        /// </summary>
        /// <returns></returns>
        public override string ToString()
        {
            return string.Format("ShaderProgram: Id:{0}", this.Id);
        }
    }
}
