using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace SoftGL
{
    partial class Framebuffer : IDisposable
    {
        private uint[] ids = new uint[1];

        /// <summary>
        /// name generated by glGenFramebuffers(..).
        /// </summary>
        public uint Id { get { return this.ids[0]; } }

        /// <summary>
        /// Creates a framebuffer object.
        /// </summary>
        public Framebuffer(uint id) { this.ids[0] = id; }

        /// <summary>
        /// glGet(GL_MAX_COLOR_ATTACHMENTS, ..);
        /// </summary>
        internal const int maxColorAttachments = 8;
        private IAttachable[] colorbufferAttachments = new IAttachable[maxColorAttachments]; // OpenGL supports at least 8 color attachement points.

        public IAttachable[] ColorbufferAttachments { get { return colorbufferAttachments; } }

        public IAttachable DepthbufferAttachment { get; set; }

        public IAttachable StencilbufferAttachment { get; set; }

    }
}
