using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace SoftGL
{
    class Framebuffer
    {
        private uint[] ids = new uint[1];

        /// <summary>
        /// name generated by glGenFramebuffers(..).
        /// </summary>
        public uint Id { get { return this.ids[0]; } }

        /// <summary>
        /// Creates a framebuffer object.
        /// </summary>
        public Framebuffer(uint id) { this.ids[0] = id; }
    }
}
