using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace SoftGL
{
    partial class Renderbuffer
    {
        private uint[] ids = new uint[1];

        /// <summary>
        /// name generated by glGenRenderbuffers(..).
        /// </summary>
        public uint Id { get { return this.ids[0]; } }

        /// <summary>
        /// Creates a render buffer object.
        /// </summary>
        public Renderbuffer(uint id) { this.ids[0] = id; }
    }
}
